### ISSUE TITLE
autostart kiosk on startup

### ISSUE THREAD

**Issue by BrendanBall** [grafana/grafana-kiosk#10]
What is the recommended way to autostart grafana-kiosk? If it's systemd can we add a template service file to the repo? I've tried setting it up with the following:
```
[Unit]
Description=Grafana Kiosk

[Service]
User=pi
Environment="DISPLAY=:0"
Environment="XAUTHORITY=/home/pi/.Xauthority"
ExecStart=/usr/bin/grafana-kiosk --URL <url>  -login-method local -username <username> -password <password> -playlist true

[Install]
WantedBy=graphical.target
```
This works, except that in the UI chrome complains with a big banner: `You are using an unsupported command-line flag: --no-sandbox. Stability and security will suffer`. This doesn't come up when I run the same grafana-kiosk command just in command line via ssh.
The [blog post](https://grafana.com/blog/2019/05/02/grafana-tutorial-how-to-create-kiosks-to-display-dashboards-on-a-tv/) was semi helpful, but it is kinda frustrating that it doesn't include how to do the full setup and just ignores the fact that you'd want this to be autostarted

EDIT: the chrome issue is because the service was running as root. I edited it to specify to run the service as the user `pi` and it works now. Can we add this service file to the repo?

**Comment by briangann** [comment]
great idea, let me try this out

**Comment by michaelp85** [comment]
This won't be a reliable way to do it, you're not necessarily guaranteed that the display and window manager will be ready in time. For example for me on slow hardware this wasn't working.

Better method would be to use your appropriate window manager startup scripts, for me this is; but for others may be xinitrc or similar. This will only fire once window manager is ready and waiting.

**/home/pi/.config/lxsession/LXDE-pi/autostart**
```
@xset s noblank
@xset s off
@xset -dpms
@sleep 10
@/usr/bin/grafana-kiosk.linux.armv7 -URL https://xxx.grafana.net/ -login-method gcom -username xxxx -password xxxxxx --kiosk-mode full
```

**Comment by BrendanBall** [comment]
For some reason I didn't get a notification, anyway thanks for the response. @michaelp85 I'm using freedesktop autostart as mentioned in the [lxde wiki](https://wiki.lxde.org/en/Autostart) along with the grafana-kiosk `-lxde` option which does most of the options you sepcified with `xset` according to [issue 9](https://github.com/grafana/grafana-kiosk/issues/9). So I just put the following file in `/home/pi/.config/autostart/grafana-kiosk.desktop`:
```
[Desktop Entry]
Type=Application
Exec=/usr/bin/grafana-kiosk -lxde ...other arguments
```
which seems to work. The kiosk has been freezing which I was fixing by just restarting the systemd service, but not sure what made it freeze so will see what happens with this way of running it.

**Comment by briangann** [comment]
The above methods and a couple more have been added to the documentation, many thanks to everyone! See PR #22 and the new section https://github.com/grafana/grafana-kiosk#automatic-startup
