### ISSUE TITLE
Grafana shared links, hidden left side, title navigation, especially how to display query criteria

### ISSUE THREAD

**Issue by blackqw** [grafana/grafana-kiosk#115]
What happened:

When I embed links to Grafana Share Dashboard in other projects, I use the parameter&kiosk to hide the left title navigation and query criteria.

What you expect to happen:

After hiding the left and head navigation, the query criteria should be displayed. What should I do?

Now:
![1](https://github.com/grafana/grafana-kiosk/assets/115542049/9e18fa12-2417-4cc7-bdda-1147176bca98)

Expected:
![2](https://github.com/grafana/grafana-kiosk/assets/115542049/3fa7781c-dd76-4032-b0c5-7893e1de57f0)

**Comment by blackqw** [comment]
@zerok @bcotton @marcusramberg @torkelo

**Comment by briangann** [comment]
not sure how this can be done, dashboards normally do not display the query editors, the only "chooser" options that are rendered are from template variables
