### ISSUE TITLE
Raspi OS bookworm not working

### ISSUE THREAD

**Issue by yulipumal** [grafana/grafana-kiosk#119]
Dear community,
the latest OS of Raspis (Bookworm) does not work. The window is now shown at all. Relates to #114.

It seems to be a bug in chromium on the RaspBerry Pi bookworm, when chromium is executed with parameter kiosk. [1](https://github.com/raspberrypi/documentation/issues/3184#issuecomment-1803460271), [2](https://forums.raspberrypi.com/viewtopic.php?t=358317) Grafana-Kiosk does exactly this, it executes: `chromium --kiosk`

Also: Since Raspi `buster` the login-method local (username and password) does not work anymore for me.

**Comment by malmr** [comment]
Unfortunately, i have the same problem. Cannot use grafana-kiosk on a new Raspi OS anymore.

**Comment by briangann** [comment]
will take a look and see what can be done (maybe adjust the parameters based on os-release)

I'll load up bookworm on a new pi and see how it behaves.  Currently running bullseye and jammy ok.

**Comment by briangann** [comment]
> Also: Since Raspi `buster` the login-method local (username and password) does not work anymore for me.

will check buster also, have only verified it is working with bullseye and jammy.

**Comment by briangann** [comment]
one item i noticed with rpi4 + bookworm (raspian) was the LXDE process hangs, disabling that option for now an it proceeds, not seeing an error with chromium.

the local login is working for me with 10.3.3 (and earlier)

**Comment by yulipumal** [comment]
perfect, already looking forward for the new release!

**Comment by malmr** [comment]
Would love to use `grafana-kiosk` on bookworm again. When will this pull request be released?

**Comment by briangann** [comment]
planning to get this released over the weekend, have a couple of new pi's ready for testing running bookworm.

**Comment by malmr** [comment]
Thanks for the info!

**Comment by abctaylor** [comment]
Hello @briangann thank you for working on this. Is there a release Raspi OS Bookworm users should use yet? Thank you.

**Comment by thelukepritchard** [comment]
Hi @briangann great job with this. Is it possible to get it merged? Looks like a concerning bug for those using Bookworm.

**Comment by yulipumal** [comment]
Thanks for your work briangann!
Could you please create a new version and a binary release soon? Thank you

**Comment by tholosi** [comment]
Hello. Worked for me when I switched from wayland to x11
