### ISSUE TITLE
it stopped working .... 

### ISSUE THREAD

**Issue by rmalchow** [grafana/grafana-kiosk#14]
hi,

we're using this on a some raspis to display metrics on the wall. two weeks ago, it stopped working.

i have a start script that connects to a VPN, and then does this:

```
/home/pi/grafana-kiosk/bin/grafana-kiosk.linux.armv7 \
  --URL https://${URL}/playlists/play/1 --playlist \
  --login-method local \
  --username ${USER}  \
  --password ${PASSWORD} \
  --kiosk-mode full \
  --lxde

```

in the log, it says this:
```
2019/11/05 16:35:27 Navigating to  https://${URL}/playlists/play/1?kiosk=1&autofitpanels
2019/11/05 16:35:34 ERROR: unhandled page event *page.EventWindowOpen
```
(with the correct URL)

on the screen, the browser opens, and then loads the grafana login page. however, it then does NOT seem to enter the credentials (this was what i could observe before), but takes me to the online documentation:
```
https://grafana.com/docs/
```
**grafana**: Grafana v6.4.3 
**chromium**: 74.0.3729.157

running on raspbian.

any ideas? could it be that they changed the login process in a way that no longer works with grafana-kiosk?

**Comment by rmalchow** [comment]
ok. some more info: i just downgraded grafana to 6.3.6. there, it does work just fine. so i guess something changed with the login form.

**Comment by briangann** [comment]
just curious did you rebuild the binary from the current "master" branch?

**Comment by rmalchow** [comment]
oh. i did pull, but i didn't rebuild. i'll check that.

**Comment by rmalchow** [comment]
ok. rebuilt it, works. thank you very much. sorry for being stupid :)
