### ISSUE TITLE
Service Account authentication always shows "Endpoint only available for users"

### ISSUE THREAD

**Issue by weng5e** [grafana/grafana-kiosk#146]
I really love the grafana-kiosk that is making it really easy to display Grafana on my office TV!

One small issue is that there is always a warning message of "Endpoint only available for users". How can I avoid showing it?

The command I use to run kiosk:
.\grafana-kiosk.windows.amd64.exe -URL=https://XXXXXXXXX -login-method apikey --apikey XXXXXX" -kiosk-mode=tv

Grafana v10.4.7 (ac358f3e56)

![Image](https://github.com/user-attachments/assets/e4581e02-7843-42c3-9afe-e3d374359fa2)

**Comment by briangann** [comment]
this looks like it was introduced in grafana v10.1.x, it is now checking the type of login being used, and puts up that warning if it is not a "real user."  

i tried both a "legacy" api key and the new service account api key and they behave the same way.

right now i don't see a way to prevent this from happening other than opening an issue with Grafana core and a PR that would prevent that popup. 

luckily the popup does go away, but this is not a good user experience.

i think api keys are really intended to be used against the `/api` path only and not as a login method, even though it does work.  i've noticed some odd side effects with this method too where plugins fail to load (one loads, the rest do not).

**Comment by weng5e** [comment]
Thanks for the quick response @briangann! All of our plugins are working correctly even with service account :)

Our usage scenario is a "typical big enterprise" office TV. Our have the below security requirements:
1. Our Grafana cannot be anonymous accessible due to the company's security requirements. 
2. It is also a common practice for big enterprise IT department to ban sharing one "user / human identity" account across the team, i.e. we cannot share a username and password auth based email. All of our user ' human accounts are enforcing multifactor authentication. MFA will make long runing TV display impossible.
3. We are running kiosk on Raspberry Pi, which is not our company IT managed device. For user accounts, our IT department only allow login on company managed devices (e.g. [Windows machines which are domain joined](https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/deployment/join-a-computer-to-a-domain)).

So, it seems like service account is our only option to use Grafana Kiosk. Is this understanding correct?

Given service account might be our only option here, it would be really nice if there is a way to hide the "Endpoint only available for users" warning.

**Comment by briangann** [comment]
I think that usage scenario is likely common, plus it doesn't rely on field searching for the login.

I'll talk to our team about this suppressing this popup for service accounts since functionally everything works.

**Comment by weng5e** [comment]
@briangann thank you so much for the information! Looking forward for addtional updates.

**Comment by weng5e** [comment]
This bug is not restricted to only the kiosk client. It is also impacting other non user scenarios, e.g. image capture in alerting and reporting.

![Image](https://github.com/user-attachments/assets/c5ca9a29-77e7-4f9a-b4c1-490b9f37daf6)

**Comment by allebone** [comment]
Nothing to add, just observing, since we’re starting the journey to kiosk and API/service account is our chosen method too!

**Comment by weng5e** [comment]
I am still repro ducing this error in 10.4.15.

**Comment by briangann** [comment]
> I am still repro ducing this error in 10.4.15.

are you running v1.0.9 of kiosk?

**Comment by weng5e** [comment]
I am using 1.0.8 of kiosk. Does this matter? This bug was marked as closed before 1.0.9 was released.

**Comment by briangann** [comment]
> I am using 1.0.8 of kiosk. Does this matter? This bug was marked as closed before 1.0.9 was released.

yes, it was closed right before the release of 1.0.9, i need to coordinate that better!

please try 1.0.9 as it contains the fixes required to make this work properly.

**Comment by weng5e** [comment]
Thanks for the inofmration! I tried kiosk 1.0.9 and it still repro.
