### ISSUE TITLE
Disable SSL verification

### ISSUE THREAD

**Issue by mehyedes** [grafana/grafana-kiosk#25]
I think it would be useful to have to possibility to disable SSL verification using an argument like `--disable-ssl-verification` for on-premise Grafana installations.

**Comment by xanmanning** [comment]
I would second a desire for `--disable-ssl-verification` as dashboards may be displayed on Raspberry Pis hooked up to a TV without a mouse and keyboard, so ignoring self-signed certificates is rather difficult.

**Comment by xanmanning** [comment]
I have created PR #26 to address this. From my testing this appears to work.

**Comment by mehyedes** [comment]
Thanks @xanmanning ! 
I will try to test this.
