### ISSUE TITLE
Chromium update pop-up

### ISSUE THREAD

**Issue by safadig** [grafana/grafana-kiosk#27]
Any recommendation for an argument that disables Chromium Update ( failed update) check? I tried adding  
`chromium-browser --check-for-update-interval=1 --simulate-critical-update` 
can help stop the pop-up.
Tried adding arguments on usr/bin/grafana-kiosk command line but no luck

**Comment by laasfuus** [comment]
Same issue has been bugging me also for a while.

**Comment by hriekehof** [comment]
i also got this problem. would be nice to get a fix for this 👍

**Comment by AlexHeylin** [comment]
If anyone can find the correct Chrome flag to disable this, I can have a go at adding to the code. 
I can't find the flag. The docs make it seem unlikely 
```
--check-for-update-interval=1 --simulate-critical-update
```
is the right way to do this, because that should cause it to simulate a critical update every 60 seconds.  @safadig are you saying for certain these flags work?

**Comment by oscni** [comment]
if running chrome browser with --simulate-critical-update flag it does not seem to pop up the the update window, instead it only displays a red arrow icon on the status bar. Only if you click the icon the pop up window will appear. How this works in full screen kiosk mode I don't know but +1 for fixing it :)

**Comment by karlbeecken** [comment]
for me it was fixed by running `sudo apt install chromium` on the pi

**Comment by liquidcards** [comment]
`sudo touch /etc/chromium-browser/customizations/01-disable-update-check;echo CHROMIUM_FLAGS=\"\$\{CHROMIUM_FLAGS\} --check-for-update-interval=31536000\" | sudo tee /etc/chromium-browser/customizations/01-disable-update-check`

from [here](https://stackoverflow.com/questions/58993181/disable-chromium-can-not-update-chromium-window-notification)

**Comment by loganmarchione** [comment]
@karlbeecken  - I did the same thing. It seems `chromium` doesn't have hardware acceleration, but that doesn't seem to be a big deal for a simple Grafana dashboard.
https://www.raspberrypi.org/forums/viewtopic.php?t=272394
https://www.raspberrypi.org/forums/viewtopic.php?t=273504

**Comment by briangann** [comment]
I'll add the flag `--check-for-update-interval=31536000` to the default startup, seems to be a good workaround.

**Comment by briangann** [comment]
fixed in v1.0.3
