### ISSUE TITLE
/usr/bin/grafana-kiosk: command not found

### ISSUE THREAD

**Issue by DennisCor** [grafana/grafana-kiosk#30]
I'm using a Raspberry Pi 3b and Grafana v6.6.1. and trying to run your grafana-kiosk tool.
But I get the error Message:
`pi@raspberrypi:~ $ sudo /usr/bin/grafana-kiosk --URL https://localhost:3000 --login-method local --username admin --password ** --kiosk-mode tv`

`sudo: /usr/bin/grafana-kiosk: Befehl nicht gefunden`

Befehl nicht gefunden = command not found

I downloade the .zip from "releases", extract _grafana-kiosk.linux.armv7_ to _/usr/bin/_ and renamed it to grafana-kiosk. Like you deskrip it in the manual. But runing the comand gets me the Err.
What am I doing wrong ?

**Comment by thirdgen88** [comment]
You might not need to run `grafana-kiosk` with `sudo`, you only need `sudo` to copy it into `/usr/bin`.  I'd try running without it, it runs fine for me on Raspberry Pi 2 Model B w/ the armv7 build.

**Comment by briangann** [comment]
can you give the output of `ls -l /usr/bin/grafana-kiosk`

the execute bit may not be set. `chmod a+x /usr/bin/grafana-kiosk`

**Comment by briangann** [comment]
will recheck the zip file, most likely this is related to the execute bit not being set.
