### ISSUE TITLE
Any plans of using ApiKeys ?

### ISSUE THREAD

**Issue by rapidos** [grafana/grafana-kiosk#33]
I see there is an option to pass a bearer token directly in the header.

Wouldn't that be an option for grafana-kiosk ?

![screencapture-grafana-modulotech-fr-org-apikeys-2020-04-18-17_08_38](https://user-images.githubusercontent.com/194068/79641359-5687b300-8197-11ea-9faf-931b10b0b484.png)

![screencapture-grafana-modulotech-fr-org-apikeys-2020-04-18-17_09_56](https://user-images.githubusercontent.com/194068/79641373-73bc8180-8197-11ea-8619-b1f1adba8b33.png)

**Comment by briangann** [comment]
the api key is for accessing the /api endpoints, they can't be used for interactive login (will double check though if this has changed)

**Comment by rapidos** [comment]
My bad, I quickly checked online and it looks like you are right. Each example I could find is API based.

**Comment by briangann** [comment]
hopefully the new config file option will help with logins too :)
