### ISSUE TITLE
"undefined: kiosk.Config" during build

### ISSUE THREAD

**Issue by gstrike** [grafana/grafana-kiosk#38]
Using the latest commit I am receiving the following when running make:

```
$ make
Building grafana-kiosk
GO111MODULE=on GOOS=darwin GOARCH=amd64 go build -o bin/grafana-kiosk.darwin pkg/cmd/grafana-kiosk/main.go
# command-line-arguments
pkg/cmd/grafana-kiosk/main.go:84:19: undefined: kiosk.Config
pkg/cmd/grafana-kiosk/main.go:100:10: undefined: kiosk.Config
Makefile:8: recipe for target 'dev' failed
make: *** [dev] Error 2

```

It looks like the kiosk.Config object isn't created.  I tried renaming this to "Args" to take advantage of the custom type at the top of main.go, but that didn't work either.  I've not really used the cleanenv library before, or even Go for that matter.  I'm probably just missing a step somewhere.

**Comment by gstrike** [comment]
I see the latest commit was for updating the code to Go 1.14.  I'm running Go 1.10.4.  Could that be the issue?

**Comment by briangann** [comment]
yes that is the reason - module support changed from 1.10 to 1.11, you'd need to have at least 1.11 to build it.  I haven't tried any other versions other than 1.13 and 1.14.
