### ISSUE TITLE
Local login requires interaction

### ISSUE THREAD

**Issue by Sillium** [grafana/grafana-kiosk#4]
I'm starting grafana-kiosk with
```
./grafana-kiosk.linux.amd64 --URL "https://<grafana-url>/playlists/play/2" --login-method local --username "<redacted>" --password "<redacted>" --kiosk-mode disabled --playlist
```
and see the screen as if I was not logged in. If I proceed to the "Sign In" button in the bottom left of the Grafana UI, I see the login form being filled in with the parameters I have passed in the command above. I am automatically logged in without clicking anything else after "Sign In".

This means, the whole kiosk is not starting without user interaction as I have to proceed to the "Sign In" button after starting. Is there any way to prevent this?

**Comment by briangann** [comment]
Which version of grafana are you using?  I only tested with 6.2 so there may be some additional login patterns that need to be detected in the code.

Let me know and I'll duplicate the setup to sort out a fix :)

Thanks!

**Comment by Sillium** [comment]
Sure, the version we're using is `Grafana v6.1.0 (03346b6)`.

Just to make sure:
- If I don't pass any cli parameters for login and then click on "Sign In", the form fields stay empty and there's no chance to proceed to the playlist (except entering the login credentials myself of course)
- If I pass the parameters as shown above and then click "Sign In", the form gets filled in and then submitted without further action by me. I am then redirected to the playlist.

Thanks for having a look!

**Comment by Sillium** [comment]
We just tried updating Grafana to 6.2.2 and the behaviour is the same. Login works with pre-filled username and password (= values given as cli parameters to grafana-kiosk) - but only after clicking "Sign In" in the Grafana UI.

**Comment by benoitm76** [comment]
I also met the bug. It appear when you have anonymous access enable.

In our case for example, we have public and private dashboards. So Anonymous access is enabled, but I want to use grafana-kiosk to display private dashboard on our monitoring TV. In this case, grafana-kiosk is not able to login automatically and only show public dashboard (and display an access denied for private ones). If I remove Anonymous access it's working properly.

**Comment by rapidos** [comment]
Hello, I have a fresh Grafana V6.7.2 running on one of our servers.

I managed to install grafana-kiosk very easily but when running the following command my raspberry PI is taken to the login page and the form inputs are **not** filled.

`/usr/bin/grafana-kiosk --URL http://redacted.host.com:3000/...full_dashboard_url...&var-name= --login-method local --username pi-kiosks --password easypassword--kiosk-mode tv --lxde` 

Any clue about what I may be doing wrong ?

**Comment by michaelbeljaars** [comment]
I am experiencing the same problem. Using a local login with grafana-kiosk does not bypass the loginscreen.

**Comment by AlexHeylin** [comment]
This is still an issue running on Windows with Grafana 7.0.0-beta3. 
```cmd
grafana-kiosk.windows.amd64.exe --URL http://127.0.0.1:3000/playlists/play/1 --login-method local --password redacted --username redacted --kiosk-mode tv
```
Thanks

**Comment by AlexHeylin** [comment]
I've submitted a PR to fix this https://github.com/grafana/grafana-kiosk/pull/34

**Comment by briangann** [comment]
a new release will be out today, thanks to @AlexHeylin

**Comment by AlexHeylin** [comment]
😁

**Comment by briangann** [comment]
release 1.0.2 is out, including this fix and v7 compatibility :)
