### ISSUE TITLE
autofit false doesn't disable autofit

### ISSUE THREAD

**Issue by karlbeecken** [grafana/grafana-kiosk#40]
I use grafana-kiosk on a RPi 2B on Raspbian 10 Buster with a config file, but when I set autofit to false it doesn't actually diable autofit.

**Comment by DO1JLR** [comment]
I have a similar problem.

The only way I can get ``autofit`` to ``false`` is to set the environment variable. The option is unfortunately ignored in the config.

[![asciicast](https://asciinema.org/a/4sGT6XpHzxMwOC1AiKeiJN3uk.svg)](https://asciinema.org/a/4sGT6XpHzxMwOC1AiKeiJN3uk)
*Don't be surprised, I was desperate and wrote it in the config in several places.*

**Comment by djschoone** [comment]
Got the same issue on the command line arguments

`/usr/bin/grafana-kiosk --URL https://grafana.url/playlists/play/1 --login-method local --username xxx --password xxx --kiosk-mode full --autofit false --playlists`

**Comment by djschoone** [comment]
Tried with a local config file, but that doesn't work either. I'm testing this on a OSx 10.11.6 with th darwin.amd64 build of 1.0.2

I took a quick peak in the code, but couldn't find any bugs yet

**Comment by djschoone** [comment]
In pkg/kiosk/config.go changing env-default on line 6 to 'false' the false is applied. When giving the argument in de config, it applies the 'true' argument as well when given.

Any known bugs in false versus true in creating structs?

`package kiosk

// Config configuration for backend
type Config struct {
	General struct {
		AutoFit     bool   `yaml:"autofit" env:"KIOSK_AUTOFIT" env-default:"false" env-description:"fit panels to screen"`
		LXDEEnabled bool   `yaml:"lxde" env:"KIOSK_LXDE_ENABLED" env-default:"false" env-description:"initialize LXDE for kiosk mode"`
		LXDEHome    string `yaml:"lxde-home" env:"KIOSK_MODE" env-default:"/home/pi" env-description:"path to home directory of LXDE user running X Server"`
		Mode        string `yaml:"kiosk-mode" env:"KIOSK_MODE" env-default:"full" env-description:"[full|tv|disabled]"`
	} `yaml:"general"`
	Target struct {
		IgnoreCertificateErrors bool   `yaml:"ignore-certificate-errors" env:"KIOSK_IGNORE_CERTIFICATE_ERRORS" env-description:"ignore SSL/TLS certificate errors" env-default:"false"`
		IsPlayList              bool   `yaml:"playlist" env:"KIOSK_IS_PLAYLIST" env-default:"false" env-description:"URL is a playlist"`
		LoginMethod             string `yaml:"login-method" env:"KIOSK_LOGIN_METHOD" env-default:"anon" env-description:"[anon|local|gcom]"`
		Password                string `yaml:"password" env:"KIOSK_LOGIN_PASSWORD" env-default:"guest" env-description:"password"`
		URL                     string `yaml:"URL" env:"KIOSK_URL" env-default:"https://play.grafana.org" env-description:"URL to Grafana server"`
		Username                string `yaml:"username" env:"KIOSK_LOGIN_USER" env-default:"guest" env-description:"username"`
	} `yaml:"target"`
}
`

**Comment by vladget** [comment]
Same. Here is workaround, i don't know why but it works with --autofit=false (with equals sign instead of space)

**Comment by djschoone** [comment]
> works with --autofit=false
Interesting find!

**Comment by victorbrca** [comment]
I tried with both the environment variable and `--autofit=false` and neither works for me.

**Comment by nitwhiz** [comment]
It still does not work via config file. Adding `--autofit=false` did not help, the environment variable `KIOSK_AUTOFIT=false` fixes it for me.
