### ISSUE TITLE
Kiosk with OAuth2

### ISSUE THREAD

**Issue by w00dst0ck** [grafana/grafana-kiosk#42]
I know it's already on the TODO list.
But I wonder if there is a way to use the kiosk at the moment if you already use OAuth2.

* Is there any progress with OAuth2 yet?
* Is there a HowTo for using the Kiosk if you already use OAuth2?

Best regards
Kai

**Comment by mistadave** [comment]
i had an Issue with a Visualisation of a Playlist in Grafana, whichs uses generic_oauth configuration with Keycloak.
I made a quick impementation for Generic Oauth in Grafana for this grafana kiosk.

I used Keycloak as Oauth provider with Grafana. If this is useful for you, just build your own Release of my fork. Link here -> [My Fork](https://github.com/mistadave/grafana-kiosk)

## Build

1. Download source code
2. Make sure you have go 1.14 or higher installed. Alternative use a Docker image (From golang:1.14 or higher)
3. cd into grafana-kiosk and run `make`

**Sample dockerfile**

```docker
FROM golang:1.15

COPY ./grafana-kiosk /home/grafana-kiosk

CMD ["bash"]
```

Best regards
Dave
