### ISSUE TITLE
--playlist should be --playlists

### ISSUE THREAD

**Issue by loganmarchione** [grafana/grafana-kiosk#46]
In the [Usage](https://github.com/grafana/grafana-kiosk#usage) section, there is an option for `--playlist`. However, the `--help` flag of the program shows `--playlists`.
```
  -playlists
        URL is a playlist
```

Can you correct this in the documentation?

**Comment by laasfuus** [comment]
Bump, run in to this as well. My installation wasn't doing auto-login any more until I fixed this.

**Comment by briangann** [comment]
that was unintended, will update the docs in the next PR.
