### ISSUE TITLE
unclutter initialization error

### ISSUE THREAD

**Issue by kskenyon** [grafana/grafana-kiosk#48]
During initialization, the unclutter command is looking for an arg for the -display variable which is not provided.  unclutter ends in an error though it still seems to work.

Kevin

**Comment by briangann** [comment]
if your environment when launching the kiosk doesn't have the variable `DISPLAY` set, it is auto-setting it for you (and XAUTHORITY), this is normal behavior. If you did have multiple X displays (uncommon now, most span multiple screens), then setting these variables would be needed.

```
2021/06/28 12:13:49 command: /usr/bin/unclutter
2021/06/28 12:13:49 arg0: -display
2021/06/28 12:13:49 DISPLAY not set, autosetting to :0.0
2021/06/28 12:13:49 DISPLAY= :0.0
2021/06/28 12:13:49 XAUTHORITY not set, autosetting
2021/06/28 12:13:49 XAUTHORITY= /home/pi/.Xauthority
```
