### ISSUE TITLE
gcom login method stopped working recently with hosted Grafana and release v1.0.2

### ISSUE THREAD

**Issue by invchar** [grafana/grafana-kiosk#55]
Hi, never submitted an issue via Github before so hopefully I am doing so correctly. Let me know if I need to correct anything or provide additional information. I am copy/pasting the info below from my post on Grafana.com community since the template there requests quite a bit of information.

What Grafana version and what operating system are you using?
Hosted Grafana v8.0.3, grafana-kiosk v1.0.2
Used on both Raspbian and Ubuntu 20.04.2 LTS

What are you trying to achieve?
Use grafana-kiosk to display a dashboard on Hosted Grafana using gcom login method

How are you trying to achieve it?
Running grafana-kiosk with -c parameter, specifying gcom login method, grafana username, password, and dashboard url

What happened?
Used to work, stopped working a couple of weeks ago. It will launch the browser and display the login page - with the button that says “Sign in with Grafana.com” but will not proceed beyond this point

What did you expect to happen?
I expected it to proceed to the sign in page which asks for username and password, perform the login, and display the dashboard

Can you copy/paste the configuration(s) that you are having problems with?
If needed I can provide screenshots or config snippets

Did you receive any errors in the Grafana UI or in related logs? If so, please tell us exactly what they were.
No

Did you follow any online instructions? If so, what is the URL?
GitHub - grafana/grafana-kiosk: Kiosk Utility for Grafana

I have searched for any other reports of this stopping working recently but haven’t been able to find anything.

I am not a professional programmer but looking in the grafana_com_login.go file, it looks like it is searching for an href with value login/grafana_com to find the login button, and looking at the sign in page I get when navigating to the dashboard URL in an incognito window, I don't think that search criteria is valid any longer. I could be wrong though. But console output stops at the line Navigating to <dashboard URL> -- no errors, simply doesn't proceed. I'm guessing it is just waiting for the href that will never load. I suppose at some point that wait would time out, causing an error, but I haven't waited that long to see. 

Let me know if I can provide any other useful information. Would be lovely to get my kiosk working again! Thanks.

**Comment by briangann** [comment]
This will be fixed in v1.0.3, the xpath changed so it doesn't match as you mentioned.

If you want it early, you can clone this PR https://github.com/grafana/grafana-kiosk/tree/20210626_fix_gcloud and build it.

It's almost ready to release, working on adding additional gcom auth methods.

**Comment by invchar** [comment]
> This will be fixed in v1.0.3, the xpath changed so it doesn't match as you mentioned.
> 
> If you want it early, you can clone this PR https://github.com/grafana/grafana-kiosk/tree/20210626_fix_gcloud and build it.
> 
> It's almost ready to release, working on adding additional gcom auth methods.

Awesome, thank you so much!
