### ISSUE TITLE
White Screen Raspberry Pi

### ISSUE THREAD

**Issue by lmorroni** [grafana/grafana-kiosk#6]
Hello, I am running Pi version 8 with everything up-to-date.  When I try to run grafana-kiosk, I get a white screen.  Here 's what I run:
````
./grafana-kiosk/bin/grafana-kiosk.linux.armv7 --URL https://play.grafana.org/playlists/play/1 --login-method anon --kiosk-mode full --lxde
````
I've tried it with and without the --lxde parameter.

My Pi shows a white screen and that is it.  I've tested this command on a mac and it works without issue using the mac version of grafana-kiosk.

Here is what I see on the command line after running the command
````
pi@mpdash:~ $ ./grafana-kiosk/bin/grafana-kiosk.linux.armv7 --URL https://play.grafana.org/playlists/play/1 --login-method anon --kiosk-mode full --lxde
2019/09/13 14:28:50 path: /home/pi
2019/09/13 14:28:50 command: /usr/bin/lxpanel
2019/09/13 14:28:50 arg0: --profile
2019/09/13 14:28:50 Waiting for command to finish...
2019/09/13 14:28:50 Command finished with error: exit status 1
2019/09/13 14:28:50 path: /home/pi
2019/09/13 14:28:50 command: /usr/bin/pcmanfm
2019/09/13 14:28:50 arg0: --desktop
2019/09/13 14:28:50 Waiting for command to finish...
2019/09/13 14:28:50 path: /home/pi
2019/09/13 14:28:50 command: /usr/bin/xset
2019/09/13 14:28:50 arg0: --desktop
2019/09/13 14:28:50 Waiting for command to finish...
2019/09/13 14:28:50 path: /home/pi
2019/09/13 14:28:50 command: /usr/bin/xset
2019/09/13 14:28:50 arg0: s
2019/09/13 14:28:50 Waiting for command to finish...
2019/09/13 14:28:50 path: /home/pi
2019/09/13 14:28:50 command: /usr/bin/xset
2019/09/13 14:28:50 arg0: -dpms
2019/09/13 14:28:50 Waiting for command to finish...
2019/09/13 14:28:50 path: /home/pi
2019/09/13 14:28:50 command: /usr/bin/xset
2019/09/13 14:28:50 arg0: s
2019/09/13 14:28:50 Waiting for command to finish...
2019/09/13 14:28:50 DISPLAY not set, autosetting to :0.0
2019/09/13 14:28:50 DISPLAY= :0.0
2019/09/13 14:28:50 XAUTHORITY not set, autosetting
2019/09/13 14:28:50 path: /home/pi
2019/09/13 14:28:50 command: /usr/bin/unclutter
2019/09/13 14:28:50 arg0: -display
2019/09/13 14:28:50 XAUTHORITY= /home/pi/.Xauthority
2019/09/13 14:28:50 Launching ANON login kiosk
2019/09/13 14:28:50 Waiting for command to finish...
````
Any ideas?
Thanks,
Larry

**Comment by briangann** [comment]
might be an issue with raspian 8 (buster), will update one of mine to troubleshoot it.

**Comment by biolan** [comment]
I have the same issue on a Raspberry Pi 3B

- Running the Kiosk give out a white screen and nothing more.
Any troubleshooting i can do ?

**Comment by briangann** [comment]
i need to load buster on mine and see what is going on

**Comment by GrexAut** [comment]
Have the same problem,  how we can help?

**Comment by lmorroni** [comment]
I upgraded to release 10 and no longer have an issue.
pi@XXX:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster


And here's my autostart line
`
@/usr/bin/grafana-kiosk --URL https://dash.XXX.com/d/1MTaPwtZz/sales?orgId=1 --playlist --login-method local --username XXXXX --password XXXX --kiosk-mode full -autofit false --lxde
`

**Comment by briangann** [comment]
My install is running 9.1. haven't tested anything lower than that version.

```
pi@seshat:~ $  lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```

**Comment by PaulGallon** [comment]
Is there a fix for this? Experiencing the same thing on Raspian 10 (buster).

**Comment by vladget** [comment]
@PaulGallon Try to run under pi user, not root

**Comment by fechnert** [comment]
This problem seems to still exist on Raspbian 9.13 (stretch).

For me it was solved by upgrading `chromium-browser` to the latest version (72.0.3626.121-0+rpt4)

**Comment by Tetsujinfr** [comment]
I have the same white screen when opening grafana on Raspian 11 (Bullseye) 32bits, with Chromium 95.0.4638.78, running on rpi3B+.
Now, started having this problem when I used mouse cursor hidding tools like unclutter or unclutter-xfixes.
When I deactivate those cursors hidding tools, grafana in kiosk mode works fine.

So I am looking for a cursor hidding solution which works with chromium/Grafana in kiosk mode, on raspian 11.
