### ISSUE TITLE
Grafana shares links, hides left side, header navigation, especially how to display query criteria

### ISSUE THREAD

**Issue by changzhichen** [grafana/grafana-kiosk#60]
What happened:
When I embedded links to the Grafana Share Dashboard in other projects, I used the parameter &kiosk to hide the left, header navigation and also the query criteria.

What you expected to happen:
After hiding the left and head navigation, the query condition should be displayed, what should I do?

now:
![a](https://user-images.githubusercontent.com/27051861/125897175-f09390ef-208e-4d3f-a27d-08bb5355eb9d.png)

expected:
![b](https://user-images.githubusercontent.com/27051861/125897190-32806bb7-b919-425e-a11f-ccbc2142d154.png)

Environment:
Grafana version: Grafana v8.0.3
Data source type & version: prometheus
OS Grafana is installed on: Linux
User OS & Browser: Linux & Chrome

**Comment by briangann** [comment]
Grafana doesn't have a mode to display the template variables and selections in kiosk mode.

**Comment by changzhichen** [comment]
thanks
