### ISSUE TITLE
AWS Managed Grafana login support

### ISSUE THREAD

**Issue by wooiliang** [grafana/grafana-kiosk#63]
Hi,

I would like to request for AWS Managed Grafana login support. I have tried `-login-method goauth` but it doesn't work.

`grafana-kiosk --URL https://g-xxxxxxxx.grafana-workspace.ap-southeast-1.amazonaws.com/playlists/play/3 --login-method goauth --username xxxxxx --password xxxxxx --auto-login true --kiosk-mode full`

Thank you!

![image](https://user-images.githubusercontent.com/6027783/137612070-d56b1f43-11f5-414c-93c0-ce328126283e.png)

**Comment by briangann** [comment]
This should be fairly straightforward to support, the login process is slightly different.
