### ISSUE TITLE
Grafana Kiosk not working with Chromium 98.0.4758

### ISSUE THREAD

**Issue by holda29** [grafana/grafana-kiosk#68]
Hello.
I am the only one not able to launch Grafana kiosk after the Chromium update?
I am on Raspbian Bullseye, and launching kiost ends in a black screen and stuck on Launching status

pi@displejpi:~ $ /usr/bin/grafana-kiosk --URL https://play.grafana.org/playlists/play/1 --login-method anon --kiosk-mode full
2022/02/24 17:58:46 No config specified, using environment and args
2022/02/24 17:58:46 AutoFit: true
2022/02/24 17:58:46 LXDEEnabled: false
2022/02/24 17:58:46 LXDEHome: /home/pi
2022/02/24 17:58:46 Mode: full
2022/02/24 17:58:46 WindowPosition: 0,0
2022/02/24 17:58:46 URL: https://play.grafana.org/playlists/play/1
2022/02/24 17:58:46 LoginMethod: anon
2022/02/24 17:58:46 Username: guest
2022/02/24 17:58:46 Password: *redacted*
2022/02/24 17:58:46 IgnoreCertificateErrors: false
2022/02/24 17:58:46 IsPlayList: false
2022/02/24 17:58:46 Fieldname Username: false
2022/02/24 17:58:46 Fieldname Username: username
2022/02/24 17:58:46 Fieldname Password: password
2022/02/24 17:58:46 AutoFit: true
2022/02/24 17:58:46 LXDEEnabled: false
2022/02/24 17:58:46 LXDEHome: /home/pi
2022/02/24 17:58:46 Mode: full
2022/02/24 17:58:46 WindowPosition: 0,0
2022/02/24 17:58:46 URL: https://play.grafana.org/playlists/play/1
2022/02/24 17:58:46 LoginMethod: anon
2022/02/24 17:58:46 Username: guest
2022/02/24 17:58:46 Password: *redacted*
2022/02/24 17:58:46 IgnoreCertificateErrors: false
2022/02/24 17:58:46 IsPlayList: false
2022/02/24 17:58:46 Fieldname Username: false
2022/02/24 17:58:46 Fieldname Username: username
2022/02/24 17:58:46 Fieldname Password: password
2022/02/24 17:58:46 DISPLAY not set, autosetting to :0.0
2022/02/24 17:58:46 DISPLAY= :0.0
2022/02/24 17:58:46 XAUTHORITY not set, autosetting
2022/02/24 17:58:46 XAUTHORITY= /home/pi/.Xauthority
2022/02/24 17:58:46 method  anon
2022/02/24 17:58:46 Launching ANON login kiosk

**Comment by briangann** [comment]
I was able to launch it with the same arguments:

grafana-kiosk v1.0.4 (arm64) on rpi4:

```
pi@pi-kiosk-3:~/kiosk $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
ii  chromium-browser                     98.0.4758.106-rpt1               arm64        Chromium web browser, open-source version of Chrome
```

output:

```LOG
pi@pi-kiosk-3:~/kiosk $ ./grafana-kiosk.linux.arm64 --URL https://play.grafana.org/playlists/play/1 --login-method anon --kiosk-mode full
2022/03/05 01:57:41 No config specified, using environment and args
2022/03/05 01:57:41 AutoFit: true
2022/03/05 01:57:41 LXDEEnabled: false
2022/03/05 01:57:41 LXDEHome: /home/pi
2022/03/05 01:57:41 Mode: full
2022/03/05 01:57:41 WindowPosition: 0,0
2022/03/05 01:57:41 URL: https://play.grafana.org/playlists/play/1
2022/03/05 01:57:41 LoginMethod: anon
2022/03/05 01:57:41 Username: guest
2022/03/05 01:57:41 Password: *redacted*
2022/03/05 01:57:41 IgnoreCertificateErrors: false
2022/03/05 01:57:41 IsPlayList: false
2022/03/05 01:57:41 Fieldname Username: false
2022/03/05 01:57:41 Fieldname Username: username
2022/03/05 01:57:41 Fieldname Password: password
2022/03/05 01:57:41 AutoFit: true
2022/03/05 01:57:41 LXDEEnabled: false
2022/03/05 01:57:41 LXDEHome: /home/pi
2022/03/05 01:57:41 Mode: full
2022/03/05 01:57:41 WindowPosition: 0,0
2022/03/05 01:57:41 URL: https://play.grafana.org/playlists/play/1
2022/03/05 01:57:41 LoginMethod: anon
2022/03/05 01:57:41 Username: guest
2022/03/05 01:57:41 Password: *redacted*
2022/03/05 01:57:41 IgnoreCertificateErrors: false
2022/03/05 01:57:41 IsPlayList: false
2022/03/05 01:57:41 Fieldname Username: false
2022/03/05 01:57:41 Fieldname Username: username
2022/03/05 01:57:41 Fieldname Password: password
2022/03/05 01:57:41 DISPLAY not set, autosetting to :0.0
2022/03/05 01:57:41 DISPLAY= :0.0
2022/03/05 01:57:41 XAUTHORITY not set, autosetting
2022/03/05 01:57:41 XAUTHORITY= /home/pi/.Xauthority
2022/03/05 01:57:41 method  anon
2022/03/05 01:57:41 Launching ANON login kiosk
2022/03/05 01:57:45 KioskMode: Fullscreen
2022/03/05 01:57:45 Navigating to  https://play.grafana.org/playlists/play/1?kiosk=1&autofitpanels
```
I did notice the kiosk did not run the other options (unclutter/etc) when using the anon login method, that's a bug.

**Comment by morphias2004** [comment]
Try turning off hardware acceleration.

![image](https://user-images.githubusercontent.com/68760693/159211706-34b86e7d-ed44-4998-b21b-03fc60483e64.png)

The problem is that the locally hosted page doesn't load and it says "Page unresponsive". But, if I press the "Exit page" button and then "Reload" button, it starts to work correctly.

After 2 days of trying to get my Grafana dashboard to auto start when my PPi boots via using the `/etc/xdg/lxsession/LXDE-pi/autostart` method, I was experiencing the exact issue described on stumbled across this page:

https://stackoverflow.com/questions/70213741/chromium-headless-page-unresponsive-but-works-on-firefox


I made the change and it immediately resolved the issue!  👍

**Comment by holda29** [comment]
Turning off HW acceleration did the trick. Thank you!
