### ISSUE TITLE
kiosk local login broken

### ISSUE THREAD

**Issue by jortkoopmans** [grafana/grafana-kiosk#7]
Grafana: 6.4.1
grafana-kiosk: amd64 (latest binary grafana-kiosk.linux.amd64) 
method: local

When using grafana-kiosk with the most recent version of grafana v6.4.1, with a local login method, it does not achieve successful login. Chrome ends up on the 'login/reset password' page (grafanarootURL/user/password/send-reset-email).

What I think is happening sequentially;

- The 'email or username' field is skipped
- The 'password' field is filled with something (probably the password?)
- The 'Forgot your password?' is clicked

I looked briefly at the code and inspected the form, I'm guessing that the name change field of the 'email or username' field might have to do something with it. I think historically it was 'username' but now it is 'user'.

**Comment by jortkoopmans** [comment]
Looking at it a bit longer, I'm not sure the 'username' field changes matter, since it does not seem used for selection. 
I'm not going to be able to provide a PR for this, because I'm not a Go programmer and I'm confused on how I would need to build the local_login functions changes which are currently a requirement for building with 'make'. Basically I can't get any changes in local_login propagated into the binary...

**Comment by briangann** [comment]
taking a look, i'll upgrade my kiosk and see what happens.

**Comment by jortkoopmans** [comment]
Ok I lied; I did manage to fix this for my setup. I'm not sure what caused the previously sent keys to fail, either something on the Grafana login page or chromedp, but this fixes it for me.
Note that I've followed the syntax of the examples (https://github.com/chromedp/examples/blob/master/keys/main.go) using the ` instead of ", but feel free to change that.

**Comment by briangann** [comment]
upgraded to 6.4.3 and i get this now, will provide a fix

**Comment by briangann** [comment]
the merged PR didn't fix it for me, will sort it out quickly, my kiosk is broken :)

**Comment by briangann** [comment]
it actually did fix the problem, i was building the source from the wrong location

**Comment by zeppmg** [comment]
hi,
i've been experiencing the same issue since i've updated grafana to v.6.4.3.
updated grafana-kiosk, problem still remains. i'm always redirected to the Reset password page.

**Comment by jortkoopmans** [comment]
@zeppmg ; Did you compile the grafana-kiosk binary yourself? Because the binaries posted in the bin folder have not been updated....
@briangann ; The binaries posted there can be confusing. Ideally for binaries the 'release' feature of github can be leveraged.

**Comment by briangann** [comment]
my mistake! i will put in a new release with the fix

#14

**Comment by zeppmg** [comment]
@jortkoopmans no i didn't compile it myself, i updated with git pull.
Regards,

**Comment by zeppmg** [comment]
Hi @briangann ,
Is there a planned date for the fix to be put online ? Still stuck here ...
Thanks in advance.
Regards,

**Comment by jortkoopmans** [comment]
Best is to compile it yourself.
But if you trust me, you can find it attached (linux amd64). 
[issue7_grafana-kiosk.linux.amd64.zip](https://github.com/grafana/grafana-kiosk/files/3911844/issue7_grafana-kiosk.linux.amd64.zip)

**Comment by zeppmg** [comment]
Thanks for your answer + tip.
Regards,

**Comment by digerata** [comment]
Ah! So building requires the source to be installed under `/home/pi/go/src/github.com/grafana/`. Move the project there and things work...

**Comment by briangann** [comment]
The CircleCI build process has been updated to create release binaries (and branches)

You can find the latest here: https://github.com/grafana/grafana-kiosk/releases

If there's interest I can split the binaries out into separate downloadable files instead of (or in addition to) a giant zip/tar file with all builds inside.

**Comment by briangann** [comment]
Fixed by #17

**Comment by briangann** [comment]
If you have any issues with the releases let me know :)
