### ISSUE TITLE
Confusing Documentation for Playlists

### ISSUE THREAD

**Issue by Kashalls** [grafana/grafana-kiosk#71]
When exploring documentation for using a configuration file, the [README states that the config can use playlists](https://github.com/grafana/grafana-kiosk#using-a-configuration-file) as a boolean. It is also shown that in the usage flags, its is declared as `-playlists` However when inspecting the [config-example](https://github.com/grafana/grafana-kiosk/blob/main/config-example.yaml) it is shown that it is `playlist`,

https://github.com/grafana/grafana-kiosk/blob/main/scripts/grafana-kiosk.service#L11 also shows that it is used as `-playlist`

I am using my install with the config.yaml and having a bit of a hard time trying to get this to work as I can't get the playlist to play automagically (which may be a me issue, but I was confused about this).

Are both supported, or only one of the two?

**Comment by HerrSubset** [comment]
I was running into the same issue. I had `playlists: true` configured in my yaml config file. When checking the logs of grafana-kiosk, it would always report 
```
grafana-kiosk[65852]: 2022/04/12 11:26:15 IsPlayList: false
```

Changing the config to `playlist: true` fixed it:
```
grafana-kiosk[67769]: 2022/04/12 11:29:20 IsPlayList: true
```


I'd be happy do make a MR to update the docs, if someone could confirm that the `-playlists` flag is indeed unsupported.
