### ISSUE TITLE
ERROR: could not unmarshal event: unknown PrivateNetworkRequestPolicy value

### ISSUE THREAD

**Issue by drjoeward** [grafana/grafana-kiosk#79]
my syslog file was spammed with error messages to the private network request policy issues.

after a lot of googling I found it is likely do to an issue in chromedp/cdproto dependency.   i updated the go manifest to the latest version of all dependencies and the error has cleared on ubuntu.  going to also try it on windows (where i was seeing the errors as well)

https://stackoverflow.com/questions/73415019/golang-chromedp-error-could-not-unmarshal-event-unknown-privatenetworkrequestp

**Comment by briangann** [comment]
i saw this as well, will open up a pr to fix it (and merge the other one to reduce cpu usage)

Thanks for your help!

**Comment by Apfelschnitten** [comment]
Hi,

I am having the same issue, but I don't understand what I have to do to fix it.
@drjoeward said "i updated the go manifest to the latest version of all dependencies and the error has cleared on ubuntu."
But how can I update the "go manifest"?
What else I can do to fix the problem?

I am running a RPi4 with the Raspbian OS on Debian Bullseye. 
- Chromium: 104.0.5112.105
- Grafana: v9.1.6
- Grafana-Kiosk: v1.0.4 (arm64)

**Comment by briangann** [comment]
a new build will be available shortly - fixes have been merged to correct this problem

**Comment by briangann** [comment]
fixed in v1.0.5, please let me know if you run into any issues.
