### ISSUE TITLE
Explanation of LXDE feature

### ISSUE THREAD

**Issue by BrendanBall** [grafana/grafana-kiosk#9]
Hi, we're setting up grafana kiosk on a raspberry pi 3, mostly following the [blog](https://grafana.com/blog/2019/05/02/grafana-tutorial-how-to-create-kiosks-to-display-dashboards-on-a-tv/). I'm confused about the LXDE option as there's no explanation and I'm unfamiliar with it. What can I do with the LXDE option? Can we add this to the documentation?

**Comment by briangann** [comment]
This is to initialize settings for the desktop

it does this:
- sets profile via lxpanel to LXDE
- sets pcmanfs profile to LXDE
- runs "xset s off" to disable screensaver
- runs "xset -dpms" to disable powersaving (prevent screen from turning off)
- runs "xset s noblank" disables blank mode for screensaver (maybe not needed)
- runs "unclutter" to hide the mouse

**Comment by BrendanBall** [comment]
Sorry didn't get a notification, thanks for the response. Can we add this to the readme or other documentation somewhere?
